import ProofsInTheBook.PlanarMapCutCapSigma

/-!
# Kernel arbitration: concrete cut-and-cap surgery numbers (Chapter 35 Jordan)

This file is a **decisive arbitration by Lean-kernel computation**.  Two agents
disagreed on the orbit numbers of the *implemented* `cutCapMap` on the triangle
sphere map (`V=3, E=3, F=2`, the 3-cycle = the whole triangle):

* `opus-facewalk2` (model outside Lean): `c = 4` components, `F' = 8`, hence
  `F' = F + 2` FALSE in general (claimed `F' = F + 2c − 2`).
* `opus-dps` (Python enumeration): `c = 2` components.

The standard surgery design intends `c = 2`, `F' = F + 2 = 4`.

We settle it inside Lean.  The library's `V/E/F` are
`Fintype.card (Quotient (cycleSetoid ·))` (classical, non-reducing) and the
implemented `cutSigma` is `noncomputable` (it uses `Classical.choice` via
`divertKind`), so `cutCapMap.σ` cannot be `#eval`'d directly.  Instead we build a
**computable mirror** of the implemented surgery — `cutAlphaC`, `cutSigmaC` —
defined by *exactly the same case logic* as `cutAlpha` / `cutSigma`, with the
`Classical.choose` existential search replaced by a decidable `List.find?` search
over `Fin len` (which returns the same unique index by the injectivity lemmas).
We then `#eval`:

* the cycle counts of `α'`, `σ'`, `φ' = σ'∘α'` (= `E'`, `V'`, `F'`), and
* the `dartStep`-component count `c` of the cut map.

The numbers printed by `lake env lean` on these `#eval`s are the verdict.
-/

namespace ProofsInTheBook.PlanarMap

open Equiv

/-! ## Generic computable orbit / component counters

We work with permutations represented as plain functions `α → α` on a `DecidableEq`
`Fintype`, and count `f`-orbits and undirected-graph components by explicit
`Finset` closures. -/

section Counters

variable {α : Type*} [DecidableEq α]

/-- The forward `f`-orbit of `x`, computed by iterating `f` at most `N` times.
`N` should be `≥ |α|`. -/
def orbitOf (N : ℕ) (f : α → α) (x : α) : List α :=
  (List.range N).map (fun k => f^[k] x)

/-- Canonical orbit representative of `x` under the permutation `f`: the element of
its forward orbit appearing earliest in the supplied universe list `univ`.  Since
`f` is a permutation the forward orbit is the whole orbit, so this is invariant on
orbits. -/
def orbitRep (univ : List α) (f : α → α) (x : α) : Option α :=
  let orb := orbitOf univ.length f x
  (univ.filter (fun y => decide (y ∈ orb))).head?

/-- Number of `f`-orbits = number of distinct canonical representatives. -/
def cycleCountC (univ : List α) (f : α → α) : ℕ :=
  (univ.map (orbitRep univ f)).dedup.length

/-! For the `dartStep` component count we use the *undirected* graph generated by
"same `σ`-orbit" (`σ.SameCycle`) and "`α`-adjacent" (`b = α a`).  `σ` is a
permutation so iterating it forward `|univ|` times yields the whole `SameCycle`
class; `α` is an involution so it supplies both directions. -/

/-- Neighbours of `x`: the whole forward `σ`-orbit together with the `α`-partner. -/
def dartNeighbors (univ : List α) (σ a : α → α) (x : α) : List α :=
  (orbitOf univ.length σ x) ++ [a x]

/-- BFS closure of the dart graph from a single seed, `|univ|+1` rounds, returned as
a sorted-deduped list (we use `List`, not `Finset`, to stay computable). -/
def reachClosure (univ : List α) (σ a : α → α) (x : α) : List α :=
  Nat.iterate
    (fun S => (S ++ S.flatMap (dartNeighbors univ σ a)).dedup)
    (univ.length + 1)
    [x]

/-- Canonical key of a component: the universe element of smallest index that lies
in the closure of `x`. -/
def compRep (univ : List α) (σ a : α → α) (x : α) : Option α :=
  let cl := reachClosure univ σ a x
  (univ.filter (fun y => decide (y ∈ cl))).head?

/-- Number of `dartStep`-components: distinct component reps over all darts. -/
def componentCountC (univ : List α) (σ a : α → α) : ℕ :=
  (univ.map (compRep univ σ a)).dedup.length

end Counters

/-! ## The concrete triangle sphere map  (V=3, E=3, F=2, χ=2)

Darts `Fin 6`:
`0 = A→B`, `1 = B→A`, `2 = B→C`, `3 = C→B`, `4 = C→A`, `5 = A→C`.

* `α = (0 1)(2 3)(4 5)`  (edge involution).
* `σ = (0 5)(1 2)(3 4)`  (vertex rotations: A={0,5}, B={1,2}, C={3,4}).
* `φ = σ∘α = (0 2 4)(1 5 3)` → two faces.
-/

namespace TriangleMap

open CombMap

/-- α as a function on `Fin 6`: swap (0 1)(2 3)(4 5). -/
def alphaF : Fin 6 → Fin 6
  | 0 => 1 | 1 => 0 | 2 => 3 | 3 => 2 | 4 => 5 | 5 => 4

/-- σ as a function on `Fin 6`: (0 5)(1 2)(3 4). -/
def sigmaF : Fin 6 → Fin 6
  | 0 => 5 | 5 => 0 | 1 => 2 | 2 => 1 | 3 => 4 | 4 => 3

/-- α is an involution (hence a `Perm` via `Involutive.toPerm`). -/
lemma alphaF_invol : Function.Involutive alphaF := by intro x; fin_cases x <;> rfl

lemma sigmaF_invol : Function.Involutive sigmaF := by intro x; fin_cases x <;> rfl

/-- The edge involution as a permutation. -/
def alphaP : Equiv.Perm (Fin 6) := Function.Involutive.toPerm alphaF alphaF_invol

/-- The vertex rotation as a permutation. -/
def sigmaP : Equiv.Perm (Fin 6) := Function.Involutive.toPerm sigmaF sigmaF_invol

/-- The triangle sphere map. -/
def triM : CombMap (Fin 6) where
  α := alphaP
  σ := sigmaP
  α_invol := by
    apply Equiv.ext
    intro x
    simp only [Equiv.Perm.mul_apply, Equiv.Perm.one_apply]
    show alphaP (alphaP x) = x
    exact alphaF_invol x
  α_no_fixed := by intro x; fin_cases x <;> decide

/-- Universe list of the 6 darts. -/
def U6 : List (Fin 6) := List.finRange 6

/-! ### Kernel check of the base map's V, E, F, χ via the computable counters -/

-- α', σ', φ' cycle counts of the *base* triangle map:
#eval cycleCountC U6 sigmaF                 -- V = 3 (expected)
#eval cycleCountC U6 alphaF                 -- E = 3 (expected)
#eval cycleCountC U6 (fun d => sigmaF (alphaF d))  -- F = 2 (expected)
-- χ = V - E + F = 3 - 3 + 2 = 2.
#eval (cycleCountC U6 sigmaF : Int)
      - cycleCountC U6 alphaF + cycleCountC U6 (fun d => sigmaF (alphaF d))

-- base-map connectivity: one dartStep component.
#eval componentCountC U6 sigmaF alphaF        -- c = 1 (connected, expected)

end TriangleMap

/-! ## The cut-and-cap surgery, computably

We replicate the implemented `cutAlpha`/`cutSigma` clause-for-clause on the cut
dart type `Fin 6 ⊕ (Fin 3 ⊕ Fin 3)`, replacing `Classical.choose` by a decidable
index search.  The cycle `C` is the whole triangle:
`dart 0 = 0, dart 1 = 2, dart 2 = 4`. -/

namespace TriangleCut

open CombMap TriangleMap

/-- The cut dart type: `6 + (3+3) = 12` darts. -/
abbrev CD := Fin 6 ⊕ (Fin 3 ⊕ Fin 3)

instance : Fintype CD := inferInstance
instance : DecidableEq CD := inferInstance

/-- Forward cycle darts `dart : Fin 3 → Fin 6`: `0 ↦ 0, 1 ↦ 2, 2 ↦ 4`. -/
def dartC : Fin 3 → Fin 6
  | 0 => 0 | 1 => 2 | 2 => 4

/-- Cyclic predecessor on `Fin 3`. -/
def prevI : Fin 3 → Fin 3
  | 0 => 2 | 1 => 0 | 2 => 1

/-- `q_i = dart i`. -/
def qD (i : Fin 3) : Fin 6 := dartC i

/-- `p_i = α (dart (prevIdx i))`. -/
def pD (i : Fin 3) : Fin 6 := alphaF (dartC (prevI i))

/-- Decidable search for the unique `i` with `pred i = some` matching; mirrors the
`Classical.choose` of `divertKind` / `cycleKind` / `startKind`. -/
def findI (pred : Fin 3 → Bool) : Option (Fin 3) :=
  (List.finRange 3).find? pred

/-! ### `cutAlphaC` — mirror of `cutAlpha`

```
inl d:  if d = dart i      ↦ c_i^+ = inr (inl i)
        if d = α (dart i)  ↦ c_i^- = inr (inr i)
        else               ↦ inl (α d)
c_i^+ ↦ inl (dart i)
c_i^- ↦ inl (α (dart i))
```
-/
def cutAlphaC : CD → CD
  | Sum.inl d =>
      match findI (fun i => decide (d = dartC i)) with
      | some i => Sum.inr (Sum.inl i)
      | none =>
        match findI (fun i => decide (d = alphaF (dartC i))) with
        | some i => Sum.inr (Sum.inr i)
        | none => Sum.inl (alphaF d)
  | Sum.inr (Sum.inl i) => Sum.inl (dartC i)
  | Sum.inr (Sum.inr i) => Sum.inl (alphaF (dartC i))

/-! ### `cutSigmaC` — mirror of `cutSigma`

```
inl d:  if σ d = p_i  ↦ c_i^+ = inr (inl i)     (divertKind = inl (inl i))
        if σ d = q_i  ↦ c_i^- = inr (inr i)     (divertKind = inl (inr i))
        else          ↦ inl (σ d)
c_i^+ ↦ inl (q_i) = inl (dart i)
c_i^- ↦ inl (p_i)
```
Note: the `p`-test takes priority over the `q`-test, exactly as `divertKind`
checks `∃ i, σ d = p_i` first. -/
def cutSigmaC : CD → CD
  | Sum.inl d =>
      match findI (fun i => decide (sigmaF d = pD i)) with
      | some i => Sum.inr (Sum.inl i)
      | none =>
        match findI (fun i => decide (sigmaF d = qD i)) with
        | some i => Sum.inr (Sum.inr i)
        | none => Sum.inl (sigmaF d)
  | Sum.inr (Sum.inl i) => Sum.inl (qD i)
  | Sum.inr (Sum.inr i) => Sum.inl (pD i)

/-! ### Print the σ' and α' tables (diagnosis) -/

/-- Encode a `CD` as an `Int` for readable printing: `inl d ↦ d`,
`c_i^+ ↦ 100 + i`, `c_i^- ↦ 200 + i`. -/
def enc : CD → Int
  | Sum.inl d => (d : Int)
  | Sum.inr (Sum.inl i) => 100 + (i : Int)
  | Sum.inr (Sum.inr i) => 200 + (i : Int)

/-- All 12 cut darts in print order: inl 0..5, c^+ 0..2, c^- 0..2. -/
def allCD : List CD :=
  ((List.finRange 6).map Sum.inl) ++
  ((List.finRange 3).map (fun i => Sum.inr (Sum.inl i))) ++
  ((List.finRange 3).map (fun i => Sum.inr (Sum.inr i)))

-- σ' table:  (enc x, enc (σ' x))
#eval allCD.map (fun x => (enc x, enc (cutSigmaC x)))
-- α' table:
#eval allCD.map (fun x => (enc x, enc (cutAlphaC x)))
-- φ' = σ' ∘ α' table:
#eval allCD.map (fun x => (enc x, enc (cutSigmaC (cutAlphaC x))))

/-! ### The kernel verdict numbers -/

-- E' = number of α'-cycles  (expected 6 = E + k = 3 + 3):
#eval cycleCountC allCD cutAlphaC
-- V' = number of σ'-cycles  (expected 6 = V + k = 3 + 3):
#eval cycleCountC allCD cutSigmaC
-- F' = number of φ'-cycles  (φ' = σ' ∘ α'):
#eval cycleCountC allCD (fun x => cutSigmaC (cutAlphaC x))
-- χ' = V' - E' + F'
#eval (cycleCountC allCD cutSigmaC : Int)
      - cycleCountC allCD cutAlphaC
      + cycleCountC allCD (fun x => cutSigmaC (cutAlphaC x))

/-! ### Component count `c` of the cut map (the heart of the conflict)

`dartStep` components are generated by the `σ'`-orbit relation and `α'`-adjacency.
We feed the plain functions `cutSigmaC` and `cutAlphaC` to the BFS closure. -/

-- c = number of dartStep-components of the cut map  (the disputed number):
#eval componentCountC allCD cutSigmaC cutAlphaC

-- Sanity: cutAlphaC and cutSigmaC are bijections (images have 12 distinct darts).
#eval (allCD.map (fun x => enc (cutAlphaC x))).dedup.length   -- expect 12
#eval (allCD.map (fun x => enc (cutSigmaC x))).dedup.length   -- expect 12

/-! ### Cross-check against the formula `F' = F + 2c − 2`

With `F = 2`: if `c = 2` then `F + 2c − 2 = 4`; if `c = 4` then `F + 2c − 2 = 8`. -/
#eval (2 + 2 * componentCountC allCD cutSigmaC cutAlphaC - 2 : Int)  -- F + 2c - 2

/-! ## The CORRECTED `σ'` (the fix), computably

Diagnosis: cap `c_i^+` pairs with `dart i = q_i` (the `+`-bank start at `v_i`), so
`c_i^+` has its *tail at `v_{i+1}^+`* (the head of `dart i`).  Hence it must be
spliced at the bank-end `ℓ_{i+1}^+ = σ⁻¹ p_{i+1}` of vertex `v_{i+1}^+`, **not** at
`ℓ_i^+`.  Equivalently, relative to the implementation the `+`-cap index is shifted
by one.  The `−` bank is already correct.  Corrected wiring:

```
σ' (ℓ_i^+) = c_{prevI i}^+      σ' (c_i^+) = inl (dart (nextI i))     -- + cap FIXED
σ' (ℓ_i^-) = c_i^-             σ' (c_i^-) = inl (p_i)                -- − cap (unchanged)
σ' (inl d) = inl (σ d)         otherwise
```

We compute this corrected mirror and confirm the design numbers
`V'=6, E'=6, F'=4, χ'=4, c=2`. -/

/-- Cyclic successor on `Fin 3` (`nextIdx`). -/
def nextI : Fin 3 → Fin 3
  | 0 => 1 | 1 => 2 | 2 => 0

/-- The corrected cut rotation, mirroring the fix in `PlanarMapCutCapSigma2.lean`.
The bank-end tests are by `σ d = p_i` / `σ d = q_i` exactly as `divertKind`. -/
def cutSigmaC2 : CD → CD
  | Sum.inl d =>
      match findI (fun i => decide (sigmaF d = pD i)) with
      | some i => Sum.inr (Sum.inl (prevI i))      -- ℓ_i^+ ↦ c_{prevI i}^+   (FIX)
      | none =>
        match findI (fun i => decide (sigmaF d = qD i)) with
        | some i => Sum.inr (Sum.inr i)            -- ℓ_i^- ↦ c_i^-
        | none => Sum.inl (sigmaF d)
  | Sum.inr (Sum.inl i) => Sum.inl (dartC (nextI i))   -- c_i^+ ↦ dart (nextI i)  (FIX)
  | Sum.inr (Sum.inr i) => Sum.inl (pD i)              -- c_i^- ↦ p_i

-- corrected σ' table:
#eval allCD.map (fun x => (enc x, enc (cutSigmaC2 x)))
-- corrected φ' = σ'₂ ∘ α':
#eval allCD.map (fun x => (enc x, enc (cutSigmaC2 (cutAlphaC x))))

-- CORRECTED verdict numbers:
#eval cycleCountC allCD cutAlphaC                              -- E' = 6
#eval cycleCountC allCD cutSigmaC2                             -- V' = 6
#eval cycleCountC allCD (fun x => cutSigmaC2 (cutAlphaC x))    -- F' = 4  (FIXED)
#eval (cycleCountC allCD cutSigmaC2 : Int)
      - cycleCountC allCD cutAlphaC
      + cycleCountC allCD (fun x => cutSigmaC2 (cutAlphaC x))  -- χ' = 4
#eval componentCountC allCD cutSigmaC2 cutAlphaC               -- c = 2  (FIXED)
-- corrected σ'₂ is a bijection (12 distinct images):
#eval (allCD.map (fun x => enc (cutSigmaC2 x))).dedup.length  -- 12

end TriangleCut

end ProofsInTheBook.PlanarMap
